# Configuration for creating netlist from Kicad schematiic

[default]
kicadCmd = "/usr/bin/kicad-cli"
schematicLoc = "."
schematicName = "my_schematic.kicad_sch"
netlistLoc = "."
netlistName = "my_netlist.cir"
deleteForwardSlashes = true

[laser_driver]
kicadCmd = "/usr/bin/kicad-cli"
schematicLoc = "/workspaces/kicad_ngspice/examples/from_kicad_distribution/laser_driver"
schematicName = "laser_driver.kicad_sch"
netlistLoc = "."
netlistName = "laser_driver.cir"
deleteForwardSlashes = true

[pspice]
kicadCmd = "/usr/bin/kicad-cli"
schematicLoc = "/workspaces/kicad_ngspice/examples/from_kicad_distribution/pspice"
schematicName = "pspice.kicad_sch"
netlistLoc = "."
netlistName = "pspice.cir"
deleteForwardSlashes = true

[rectifier]
kicadCmd = "/usr/bin/kicad-cli"
schematicLoc = "/workspaces/kicad_ngspice/examples/from_kicad_distribution/rectifier"
schematicName = "rectifier.kicad_sch"
netlistLoc = "."
netlistName = "rectifier.cir"
deleteForwardSlashes = true
