# Configuration for creating netlist from Kicad schematiic

[default]

[laser_driver]
kicadCmdLoc = "C:/PROGRA~1/kicad/7.0/bin/kicad-cli.exe"
schematicLoc = "G:/My Drive/_TechSharpen/ngspice_work/projects/kicad_netlister/kicad_sim_examples/laser_driver"
schematicName = "laser_driver.kicad_sch"
netlistLoc = "G:/My Drive/_TechSharpen/ngspice_work/projects/kicad_netlister"
netlistName = "laser_driver.cir"
deleteForwardSlashes = true
