# Configuration for creating netlist from Kicad schematiic

[default]
kicadCmd = "/usr/bin/kicad-cli"
schematicLoc = "."
schematicName = "my_schematic.kicad_sch"
netlistLoc = "."
netlistName = "my_netlist.cir"
deleteForwardSlashes = true


[laser_driver]
kicadCmd = "/usr/bin/kicad-cli"
schematicLoc = "/workspaces/kicad_ngspice/examples/from_kicad_distribution/laser_driver"
schematicName = "laser_driver.kicad_sch"
netlistLoc = "."
netlistName = "laser_driver.cir"
deleteForwardSlashes = true
